### PR TITLE
Programs C++,this includes all the problems related to c++

### PR DESCRIPTION
**Pull request by Vaishwanavi**

### CODE REVIEW

**Comment by thakurdiwakar** [comment]
@Vaishwanavi  Kindly create a directory named "Programs/C++/your_files" and move your C++ program into it. Please ensure that you update the readme file as well. Additionally, provide an appropriate title and description for your pull request

**Comment by Vaishwanavi** [comment]
@thakurdiwakar okk

**Comment by Vaishwanavi** [comment]
@thakurdiwakar  please now check and review #34

**Comment by thakurdiwakar** [comment]
@Vaishwanavi **could you please read the comment properly?**

**Comment by thakurdiwakar** [comment]
> @Vaishwanavi Kindly create a directory named "Programs/C++/your_files" and move your C++ program into it. Please ensure that you update the readme file as well. Additionally, provide an appropriate title and description for your pull request



please follow the instructions @Vaishwanavi

**Comment by thakurdiwakar** [comment]
@Vaishwanavi I have added the directories please push your code according to the topic

**Pull request closed without merging**
