### PR TITLE
Arranged All sections in readme.md added some icons , corrected some typos , changed the Name of the folder to upper case

### PR DESCRIPTION
**Pull request by ankit1576**
Changed All the Folder name as (on issue #73) which is in smaller case such as java.md--> Java , coding.md--> Coding Concepts, dbms.md-->DBMS(Database Management System) like wise i have changed all the name of the folder and after that updated all the hyperlinks in the Readme.md file for new Folder name and Arrange all the Paragragh in a way it is written on Index table 
Added Common Job interview Question reference Answers mention on issue #77 and updated readme.md file with its hyperlinks

### CODE REVIEW

**Comment by ankit1576** [comment]
All folder name changed to upper case like java.md--> Java like that i have changed all the folder names with the references in readme.md please review and check and comment is any more changes required

**Comment by thakurdiwakar** [comment]
@ankit1576 , some topic links are not working. Please provide a proper description for your pull request and include the issue number.

**Comment by ankit1576** [comment]
> @ankit1576 , some topic links are not working. Please provide a proper description for your pull request and include the issue number.

yes updated the description , now working on not working hyperlink on index table

**Comment by ankit1576** [comment]
@thakurdiwakar Completed all checks and dropped the idea of adding icon as it is creating problem with hyperlinks
merge this Pr now everything working fine

**Comment by thakurdiwakar** [comment]
@ankit1576 nice

**Comment by thakurdiwakar** [comment]
@ankit1576 okay

**Pull request merged**
