### PR TITLE
added github resource

### LINKED ISSUE #96: I have a new github resource
I have a new github resource, can you assign me the task so that I can contribute?

### PR DESCRIPTION
**Pull request by A10-g**
## Checklist before requesting a review

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have performed a self-review of my code
- [ ] I have updated a `README.md`.
- [ ] I have added screenshots (if any) that prove my fix is effective or that my feature works.

Note: To check a box, replace the space inside the square brackets with an 'x'.

### CODE REVIEW

**Comment by A10-g** [comment]
Feel free to ask or any changes

**Comment by thakurdiwakar** [comment]
image

@A10-g You have ticked certain points but have not completed them.,updated them

**Comment by A10-g** [comment]
> image
> 
> @A10-g You have ticked certain points but have not completed them.,updated them

ok I'll make changes

**Comment by A10-g** [comment]
@thakurdiwakar check now

**Comment by thakurdiwakar** [comment]
image
Fix it

image

check the file name 11.md and index no,. is 13

**Comment by A10-g** [comment]
Hi @thakurdiwakar I have removed readme since the repo ink will be reflected only after merging 
Also I have renamed file from 11.md to 13.md

**Pull request merged**
