### PR TITLE
Updated java-program.md file

### LINKED ISSUE #87: I have few Java Programming Questions  to add
## Describe the question/project you want to add with tech stack
 I Have few java Programing questions  which I want to add

## Expected behavior
 6 programs on java language(palindrome, reverse no. etc .

### PR DESCRIPTION
**Pull request by Ankita-0302**
## Describe your changes
updated the file again
## Checklist before requesting a review

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have performed a self-review of my code
- [x] I have updated a `README.md`.
- [x] I have added screenshots (if any) that prove my fix is effective or that my feature works.

Note: To check a box, replace the space inside the square brackets with an 'x'.

### CODE REVIEW

**Comment by Ankita-0302** [comment]
On my repository it is opening properly

i1

**Comment by Ankita-0302** [comment]
please check and tell me again I will try it again.

**Comment by thakurdiwakar** [comment]
@Ankita-0302 When clicking on the questions in the readme.md file, they are not opening

**Comment by Ankita-0302** [comment]
Can you please give me SS ............it is opening on my repository

**Comment by thakurdiwakar** [comment]
image

image


these two are not opening

**Comment by thakurdiwakar** [comment]
image

image


these two are not opening

**Comment by Ankita-0302** [comment]
Now try once again, for now I have deleted that two programs.

**Pull request merged**
