### PR TITLE
added - two important questions in frontend interviews

### PR DESCRIPTION
**Pull request by Ashutosh-Patel028**
Added important interview questions related to  React JS

### CODE REVIEW

**Comment by Ashutosh-Patel028** [comment]
hey @thakurdiwakar  Can you pls. check my PR.

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 update readme.md

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 Please push the questions to the directory related to the topic

**Comment by Ashutosh-Patel028** [comment]
Done @thakurdiwakar

**Comment by thakurdiwakar** [comment]
add react questions in react.md and js question in js.md

**Comment by Ashutosh-Patel028** [comment]
Sure @thakurdiwakar let me correct this.

**Comment by Ashutosh-Patel028** [comment]
Hey @thakurdiwakar, I updated React questions and README as per the given directory. Pls, have a look.

**Pull request merged**
