### PR TITLE
Doc.  Added question - Normalisation in DBMS? (frequently asked in interviews)

### PR DESCRIPTION
**Pull request by Ashutosh-Patel028**
Hi @thakurdiwakar, I have updated README and added a new Question **ques14**

### CODE REVIEW

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 Please provide a suitable title for your pull request.

**Comment by Ashutosh-Patel028** [comment]
Done @thakurdiwakar , Pls. have a look.

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 well done

**Comment by Ashutosh-Patel028** [comment]
ThankYou @thakurdiwakar 😊

**Pull request merged**
