### PR TITLE
DBMS-Normalization

### PR DESCRIPTION
**Pull request by Ashutosh-Patel028**
Answered essential questions asked in the interview i.e. Database Normalization!!

### CODE REVIEW

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 update the readme for the same

**Comment by Ashutosh-Patel028** [comment]
Sure, Thank You.

**Comment by Ashutosh-Patel028** [comment]
Hey @thakurdiwakar , Updated README.md Can u check, please. Thnx

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028 Create file name according to the question indexing .

**Comment by Ashutosh-Patel028** [comment]
@thakurdiwakar  Previous Indexing is wrong in the README.md file for question 11,12,13 is mentioned in the readme doesn't exist in the main repo and links to these questions are personal repos of previous contributors.
Can you verify once?

**Comment by thakurdiwakar** [comment]
@Ashutosh-Patel028  fixed now you can create files acc. to index no. of question.

**Pull request closed without merging**
